[api]
uri = "https://notice-board-supabase.itsup.dev"
service_key = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTczNzE4Mzk2MCwiZXhwIjo0ODkyODU3NTYwLCJyb2xlIjoic2VydmljZV9yb2xlIn0.Fj_NdyMM4AN3ARrDqWXMRsTPFC5uzr3yvWkaH-ySvRo"