"use client"

import * as React from "react"
import { 
  AlertCircle, 
  Bell, 
  Building2, 
  Calendar, 
  Camera, 
  Coffee,
  Computer,
  CreditCard,
  Database,
  Gift,
  GraduationCap,
  HelpCircle,
  Home,
  Hotel,
  Info,
  Key,
  Lock,
  LucideIcon,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Music,
  Package,
  Phone,
  School,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Store,
  Truck,
  Unlock,
  User,
  Users,
  Video,
  Wine,
  Wrench,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Building,
  Briefcase,
  DollarSign,
  ShoppingCart,
  Tag,
  PartyPopper,
  Cake,
  Film,
  Image,
  BookOpen,
  Presentation,
  MessagesSquare,
  Smartphone,
  Laptop,
  Globe,
  Cloud,
  ServerIcon,
  KeyRound,
  LockKeyhole
} from "lucide-react"
import { Notice } from "@/types/notice"

export function getCategoryIcon(category: Notice['category']) {
  if (!category) return null;
  
  const categoryName = typeof category === 'string' ? category : category.name;
  
  const iconMap: Record<string, LucideIcon> = {
    announcement: Bell,
    advertisement: Megaphone,
    promotion: AlertCircle,
    event: Calendar,
    alert: AlertTriangle,
    info: Info,
    warning: AlertTriangle,
    success: CheckCircle,
    error: XCircle,
    help: HelpCircle,
    question: HelpCircle,
    settings: Settings,
    user: User,
    users: Users,
    group: Users,
    team: Users,
    organization: Building2,
    building: Building,
    home: Home,
    office: Building2,
    work: Briefcase,
    business: Briefcase,
    finance: DollarSign,
    money: DollarSign,
    payment: CreditCard,
    card: CreditCard,
    shopping: ShoppingBag,
    cart: ShoppingCart,
    store: Store,
    shop: Store,
    market: Store,
    sale: Tag,
    discount: Tag,
    offer: Tag,
    gift: Gift,
    present: Gift,
    package: Package,
    delivery: Truck,
    shipping: Truck,
    truck: Truck,
    transport: Truck,
    travel: MapPin,
    vacation: MapPin,
    holiday: PartyPopper,
    hotel: Hotel,
    restaurant: Coffee,
    food: Coffee,
    drink: Coffee,
    coffee: Coffee,
    beer: Wine,
    wine: Wine,
    cocktail: Wine,
    party: PartyPopper,
    celebration: PartyPopper,
    birthday: Cake,
    cake: Cake,
    music: Music,
    movie: Film,
    film: Film,
    video: Video,
    camera: Camera,
    photo: Camera,
    picture: Image,
    image: Image,
    gallery: Image,
    album: Image,
    book: BookOpen,
    education: GraduationCap,
    school: School,
    university: GraduationCap,
    graduation: GraduationCap,
    certificate: GraduationCap,
    diploma: GraduationCap,
    course: BookOpen,
    class: BookOpen,
    training: BookOpen,
    workshop: Wrench,
    seminar: Presentation,
    conference: Presentation,
    meeting: Presentation,
    presentation: Presentation,
    speech: Presentation,
    talk: Presentation,
    discussion: MessagesSquare,
    chat: MessageCircle,
    message: MessageCircle,
    mail: Mail,
    email: Mail,
    phone: Phone,
    call: Phone,
    mobile: Smartphone,
    tablet: Smartphone,
    laptop: Laptop,
    desktop: Computer,
    computer: Computer,
    device: Computer,
    technology: Wrench,
    internet: Globe,
    network: Globe,
    cloud: Cloud,
    server: ServerIcon,
    database: Database,
    security: ShieldCheck,
    lock: Lock,
    unlock: Unlock,
    key: KeyRound,
    password: LockKeyhole,
    access: Key
  }

  const IconComponent = iconMap[categoryName]
  return IconComponent ? <IconComponent className="h-4 w-4" /> : null
} 